"""Added account table

Revision ID: 183ecdb6cf6c
Revises: 9391327ff420
Create Date: 2019-09-04 19:48:48.391287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183ecdb6cf6c'
down_revision = '9391327ff420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
