"""Added account table

Revision ID: 1b86665188b5
Revises: 202029d25e6d
Create Date: 2019-09-04 17:45:58.270206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b86665188b5'
down_revision = '202029d25e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('count_rep', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('full_rep', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reputation')
    op.drop_column('users', 'full_rep')
    op.drop_column('users', 'count_rep')
    # ### end Alembic commands ###
