"""Added account table

Revision ID: 1ecd26c20e99
Revises: a6ec6cb8b3cc
Create Date: 2019-09-04 20:21:26.666422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecd26c20e99'
down_revision = 'a6ec6cb8b3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
