"""Added account table

Revision ID: 202029d25e6d
Revises: 450434548e46
Create Date: 2019-09-04 17:30:30.422195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202029d25e6d'
down_revision = '450434548e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
