"""Added account table

Revision ID: 9391327ff420
Revises: 6eca31673811
Create Date: 2019-09-04 19:19:57.258309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9391327ff420'
down_revision = '6eca31673811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
