"""Added account table

Revision ID: a6ec6cb8b3cc
Revises: c8cfd79443b9
Create Date: 2019-09-04 20:11:30.532285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ec6cb8b3cc'
down_revision = 'c8cfd79443b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_user', sa.BigInteger(), nullable=False),
    sa.Column('s_user', sa.BigInteger(), nullable=True),
    sa.Column('first_message_time', sa.DateTime(), nullable=True),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=True),
    sa.Column('find_sex', sa.String(length=8), nullable=True),
    sa.Column('find_age', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vkid', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=False),
    sa.Column('count_rep', sa.Integer(), nullable=True),
    sa.Column('full_rep', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=8), nullable=True),
    sa.Column('find_sex', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
