"""Added account table

Revision ID: c8cfd79443b9
Revises: 183ecdb6cf6c
Create Date: 2019-09-04 20:10:04.455742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cfd79443b9'
down_revision = '183ecdb6cf6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
