"""Added account table

Revision ID: ddeafdbe94e4
Revises: 1b86665188b5
Create Date: 2019-09-04 18:00:34.656216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeafdbe94e4'
down_revision = '1b86665188b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 's_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 's_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
